spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    hikari:
      schema: task
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password

PaymentFinishedJobProperties:
  timeToFinish: 5