spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_schema: saga
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?saga
    hikari:
      schema: saga
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
