spring:
  datasource:
    url: jdbc:tc:postgresql:13.2://localhost/myappdb
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
    username: postgres
    password: password
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect



